name: idena_lib_dart
description: Idena dart library for Flutter based on Official Idena Backoffice
homepage: https://github.com/redDwarf03/idena_lib_dart

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Localization
  intl: ^0.17.0

  # Easy hexadecimal encoding and decoding
  hex: ^0.2.0
  
  crypto: ^3.0.1

  fixnum: ^1.0.0 

  convert: ^3.0.0

  sha3: ^0.2.0

  web3dart: ^2.1.4
  
  ecdsa: ^0.0.4

  elliptic: ^0.3.1
  
  # BigDecimal alternative
  decimal: ^1.1.0

  # Logger
  logger: ^1.0.0
  
  # HTTP client
  http: ^0.13.3
  
  pointycastle: ^3.1.1
  
  # Validation utilities
  validators: ^3.0.0
  
  protobuf: ^2.0.0

  asn1lib: ^1.0.2
 
  bip32: ^2.0.0

  bip39: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
