name: idena_lib_dart
description: Idena dart library for Flutter based on Official Idena Backoffice
homepage: https://github.com/redDwarf03/idena_lib_dart

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  intl: ^0.17.0
  
  sha3: ^0.2.0

  web3dart: ^2.1.4
  
  # BigDecimal alternative
  decimal: ^1.1.0

  # Logger
  logger: ^1.0.0
  
  # HTTP client
  http: ^0.13.3
  
  pointycastle: ^3.1.1
  
  # Vibrate (utilisé par web_crypto......)
  vibration: ^1.7.4-nullsafety.0

  # Validation utilities
  validators: ^3.0.0
  
  protobuf: ^2.0.0

  asn1lib: ^1.0.2

  bip32: ^2.0.0

  bip39: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
